"""Aded fields

Revision ID: 9b26930ae5ef
Revises: b1be74cc7463
Create Date: 2024-06-12 22:01:28.748151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b26930ae5ef'
down_revision: Union[str, None] = 'b1be74cc7463'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('input_file', sa.String(), nullable=True))
    op.add_column('results', sa.Column('output_file', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results', 'output_file')
    op.drop_column('results', 'input_file')
    # ### end Alembic commands ###
